### PR TITLE
Kirkstone humble rethinkrobotics

### PR DESCRIPTION
**Pull request by maseabunikie**

### CODE REVIEW

**Comment by jari-hodju** [comment]
Which way is this going? Master to kirkstone... or vice versa? PR says something but there is also this [commit](https://github.com/tiiuae/meta-ros/pull/3/commits/057be21e296072ebe1d67a5fae2188e8aa64ebc9) which is the other way around.

**Review by mehmetkillioglu — APPROVED** [review]
Lot of changes, hard to identify possible problems. But since it worked, we can merge it.

**Review by TimoSairiala — APPROVED** [review]
I agree, it is impossible to review so let's merge it as it is tested

**Comment by maseabunikie** [comment]
@jari-hodju The merge is happening to master. The last commit is a conflict fix which I did in the last moment.

**Pull request merged**
